### ISSUE TITLE
use relative paths

### ISSUE THREAD

**Issue by rimmesbe** [AlienLive/prj-rev-bwfs-dasmoto#1]
You want to use relative paths when you are linking css files and image files. Right now you are using absolute paths which will only work on your computer. The relative path is the path from one file directly to the other: "./resources/style.css"

https://github.com/AlienLive/prj-rev-bwfs-dasmoto/blob/master/DasMotosArts%26Crafts/index.html#L5

**Comment by AlienLive** [comment]
reviewed and edited
