### ISSUE TITLE
html sections

### ISSUE THREAD

**Issue by rimmesbe** [AlienLive/prj-rev-bwfs-dasmoto#2]
Good job using divs to create sections in your html. I would recommend putting the ids on the divs instead of the h2's so that you can differentiate between the sections. Then you can chain through the div id to target the h2s uniquely: #brushes h2 { }
Also, try to clean up the html a little: avoid random blank lines in sections and keep indentation consistent. Makes it a lot easier to read.
<img width="122" alt="screen shot 2017-06-28 at 1 57 34 pm" src="https://user-images.githubusercontent.com/9957628/36917072-c86325ce-1e23-11e8-91c7-f7f64a7c6a15.png">
https://github.com/AlienLive/prj-rev-bwfs-dasmoto/blob/master/DasMotosArts%26Crafts/index.html#L17-L25

**Comment by AlienLive** [comment]
reviewed and edited
