### ISSUE TITLE
use alt attributes on image tags

### ISSUE THREAD

**Issue by rimmesbe** [AlienLive/prj-rev-bwfs-dasmoto#3]
Try to get in the habit of describing your images with the alt attribute. This description will show up in case the image doesn't load, it is read by screen readers for accessibility purposes, and it makes your code look more professional.
https://www.codecademy.com/articles/accessibility

https://github.com/AlienLive/prj-rev-bwfs-dasmoto/blob/master/DasMotosArts%26Crafts/index.html#L20

**Comment by AlienLive** [comment]
reviewed and edited
