### ISSUE TITLE
keep your CSS DRY

### ISSUE THREAD

**Issue by rimmesbe** [AlienLive/prj-rev-bwfs-dasmoto#4]
DRY (Don't Repeat Yourself) is a common phrase used in programming. It basically means don't repeat code you've already written. Here you can see each h2 is being given the color white. It would be better to just set it for all those elements in just 1 selector rather than 3.
h2 { color: white; }
or more realistically create a new class for them. 

https://github.com/AlienLive/prj-rev-bwfs-dasmoto/blob/master/DasMotosArts%26Crafts/resources/index.css#L12-L25

**Comment by AlienLive** [comment]
reviewed and edited
