### ISSUE TITLE
CSS naming

### ISSUE THREAD

**Issue by rimmesbe** [AlienLive/prj-rev-bwfs-dasmoto#5]
"blue" as a class name is kind of an outdated form of naming convention in CSS. Modern CSS naming conventions follow a more component-driven naming style, which is found to be more reusable and easier to manage:
.price { }
Price is the component, it is descriptive and can be used throughout the pages that require price components. Check out the BEM naming convention if you are interested in this: http://getbem.com/introduction/

https://github.com/AlienLive/prj-rev-bwfs-dasmoto/blob/master/DasMotosArts%26Crafts/resources/index.css#L27-L30

**Comment by AlienLive** [comment]
reviewed and edited
